### ISSUE TITLE
Configure doorkeeper gem as OAuth Provider

### ISSUE THREAD

**Issue by intelli7** [numedik/nmcore#1]
Configure doorkeeper gem as OAuth Provider

1) Use [doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) gem 
2) set nmcore as oauth provider for nmweb & nmadmin

**Comment by twdamhore** [comment]
i think nmauth should be the provider for (a) nmcore + (b) nmweb + (c) nmadmin. so in total we would have 4 modules.

**Comment by intelli7** [comment]
why we cannot set nmcore as provider? nmadmin&nmweb access nmcore. not vice versa

**Comment by twdamhore** [comment]
this is how i see it.
(a) nmcore => 100% pure REST. will access the db. no ui.
(b) nmweb => public facing. will call nmcore REST web service. uses sinatra. no db access.
(c) nmadmin => admin. will call nmcore REST web service. uses sinatra. no db access.
(d) nmauth => uses doorkeeper. has UI. will access the db for authentication.
reason to keep as different app (a) and (d) is that I prefer to keep (a) as having no UI because 
- I want to minimize the test.
- I do not want to redeploy the nmauth code everytime we change nmcore

However I am not sure that this will work.

any compelling reasons to make nmcore as the OAuth provider?

**Comment by jimanx2** [comment]
agreed with @ttwd80

**Comment by intelli7** [comment]
ok agreed. who will handle this? @ttwd80 or @jimanx2 ?

**Comment by twdamhore** [comment]
I will handle it.

Will require assistance

—

**Comment by intelli7** [comment]
i think it's not nesessary to use rails for oauth.. any languange possible.

**Comment by twdamhore** [comment]
Agreed.

But i think doorkeeper is our best option for now

—

**Comment by intelli7** [comment]
ok.
